### ISSUE TITLE
Old maven repo in pom.xml

### ISSUE THREAD

**Issue by tomas-pluskal** [PRIDE-Utilities/jmzml#19]
The pom.xml of jmzml references a defunct maven repo:
````
       <repository>
            <id>nexus-ebi-repo-old</id>
            <url>http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/</url>
        </repository>
````

This causes maven builds to fail:
````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.768 s
[INFO] Finished at: 2016-11-20T21:38:57+00:00
[INFO] Final Memory: 14M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mzmine2: Could not resolve dependencies for project io.github.mzmine:mzmine2:jar:2.22: Failed to collect dependencies at uk.ac.ebi.jmzml:jmzml:jar:1.7.5 -> psidev.psi.tools:xxindex:jar:0.17 -> cpdetector:cpdetector:jar:1.0.7: Failed to read artifact descriptor for cpdetector:cpdetector:jar:1.0.7: Could not transfer artifact cpdetector:cpdetector:pom:1.0.7 from/to nexus-ebi-repo-old (http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/): Failed to transfer file: http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/cpdetector/cpdetector/1.0.7/cpdetector-1.0.7.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
````

**Comment by Tobias-Ternent** [comment]
Hi @tomas-pluskal I have deployed a new snapshot of this library: 1.7.6-SNAPSHOT

The unit tests are failing, they will need to be fixed before a properly deployment is done.

**Comment by Tobias-Ternent** [comment]
I've deployed the proper release version now after updating the unit test files: 1.7.7.

Please can you give that a try now, and let me know if it works OK now?

**Comment by tomas-pluskal** [comment]
Hi, thanks for the response.

Unfortunately, I am still getting the same error with referring to the updated version (1.7.6 - I guess you wrote 1.7.7 by mistake?):

[ERROR] Failed to execute goal on project msdk-io-mzml: Could not resolve dependencies for project io.github.msdk:msdk-io-mzml:jar:0.0.7-SNAPSHOT: Failed to collect dependencies at uk.ac.ebi.jmzml:jmzml:jar:1.7.6 -> psidev.psi.tools:xxindex:jar:0.17 -> cpdetector:cpdetector:jar:1.0.7: Failed to read artifact descriptor for cpdetector:cpdetector:jar:1.0.7: Could not transfer artifact cpdetector:cpdetector:pom:1.0.7 from/to intact.nexus (http://www.ebi.ac.uk/intact/maven/nexus/content/groups/public/): Failed to transfer file: http://www.ebi.ac.uk/intact/maven/nexus/content/groups/public/cpdetector/cpdetector/1.0.7/cpdetector-1.0.7.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]

**Comment by tomas-pluskal** [comment]
I guess the xxindex dependency has to be updated to 0.18, because the old repository also appears in the pom.xml of xxindex 0.17

**Comment by Tobias-Ternent** [comment]
Hi again, sorry about this, I noticed there was a problem with a dependency within xxindex. I've updated that now and released a new version of xxindex, and I've just released another version of jmzml, we're now on: 1.7.7

Other libraries that are using xxindex will need to be similarly updated too.

**Comment by tomas-pluskal** [comment]
jmzml seems to work fine now. 
Could you also update the xxindex dependency in jmzreader? 
https://github.com/PRIDE-Utilities/jmzReader/blob/master/pom.xml

**Comment by Tobias-Ternent** [comment]
Sure, I'll make time to release jmzReader as well. I have setup trouble with my machine when I tried to release it earlier today, will try again using another machine later.

**Comment by Tobias-Ternent** [comment]
Hi @tomas-pluskal I've made a new release of jmzReader to fix the xxindex dependency, hope this works OK for you now: https://github.com/PRIDE-Utilities/jmzReader

**Comment by tomas-pluskal** [comment]
Thanks for the fixes!
